version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/garu main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    clean:
        desc: Remove PKGBUILDS
        cmds:
        - sudo rm /tmp/PKGBUILD /tmp/.SRCINFO
